services:
  flask:
    build: .
    container_name: flask_app
    environment:
      - REDIS_URL=redis://redis:6379
      - FLASK_ENV=production
    expose:
      - "5000"               # expose internally to nginx
    depends_on:
      - redis

  redis:
    image: redis:7-alpine
    container_name: redis_server
    restart: always
    ports:
      - "6379:6379"          # optional: expose redis to host for debugging

  nginx:
    image: nginx:alpine
    container_name: nginx_proxy
    ports:
      - "80:80"              # host:container
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - flask
